name: Assignment 4 Test Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies from requirements.txt inside the 'flask_app' directory
      - name: Install dependencies
        run: |
          cd flask_app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up MongoDB credentials as environment variables
      - name: Set up MongoDB environment variables
        run: |
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> $GITHUB_ENV
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> $GITHUB_ENV

      # Step 5: Run the tests located in 'flask_app/tests'
      - name: Run Tests in 'flask_app/tests'
        run: |
          cd flask_app
          python -m unittest discover tests
